### ISSUE TITLE
Missing functionality - when out of band operations are done to Synthetics Tests (checks), terraform plan does not catch those.

### ISSUE THREAD

**Issue by joepsplunk** [splunk/terraform-provider-synthetics#18]
This provider is missing this functionality:

- when out of band operations are done to Synthetics Tests (checks), terraform plan does not catch those.

- it errors out with “Record not found” if a Synthetic Test (check) was created using the Terraform provider, but deleted using Synthetics UI in Splunk O11Y Cloud.

- same situation when attributes are updated, for example, Status changed from Active to Inactive using the UI.

**Comment by greatestusername-splunk** [comment]
https://github.com/splunk/terraform-provider-synthetics/pull/22
Has been merged and provides full read capabilities again.

Release `2.0.0` addresses this issue. Please re-open a new issue if you run into it again.

Thanks!
