### ISSUE TITLE
Synthetic detector

### ISSUE THREAD

**Issue by akmaanai** [splunk/terraform-provider-synthetics#27]
In the console after you have created test, specifically Uptime test - http check, it's possible to create detector for this test. But I can not find a resource in terraform provider to create detector linked to previously created uptime test. My question is do you provide terraform resource to manage detectors in Splunk Observability Synthetics?

**Comment by leij-splunk** [comment]
This is a workaround. I believe you can use the signalFx Terraform detector resource to create the uptime check.
<img width="1482" alt="image" src="https://github.com/splunk/terraform-provider-synthetics/assets/92119554/6c1345a0-4334-48a2-a01c-b5894942c219">
 I'm not sure if this is helpful or suitable for your specific case.

**Comment by greatestusername-splunk** [comment]
Going to close this issue. Please feel free to re-open if you think there is something we can address in this provider.

Thanks again for posting!
