### ISSUE TITLE
Plans fail if synthetics api test is deleted outside of terraform

### ISSUE THREAD

**Issue by rickys-splunk** [splunk/terraform-provider-synthetics#32]
It appears as though the provider does not properly recognize when a resource no longer exists. In this case, the API returns a 404 and this JSON payload: 
```json
{"message":"Record not found"}
```

The provider throws an error.
```Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Status Code: 404 Not Found
│ Response: {"message":"Record not found"}
│ 
│   with synthetics_create_api_check_v2.example_api_test[0],
│   on ../example_test.tf line 16, in resource "synthetics_create_api_check_v2" "example_api_test":
│   16: resource "synthetics_create_api_check_v2" "example_api_test" {
│ 
╵
```

Steps to reproduce:

1. Define a `synthetics_create_api_check_v2` resource
2. `terraform apply`
3. Delete that test in the Splunk Observability UI
4. `terraform plan`

**Comment by greatestusername-splunk** [comment]
Thank you for posting this issue!
Will be triaging this ticket and prioritize the work.

Otherwise if you'd like to contribute a fix yourself please feel free to do so. :)

**Comment by greatestusername-splunk** [comment]
@rickys-splunk `v2.0.4` is out to fix this. Please let me know if you run into issues with the fix or have any other questions related to this issue.
