### ISSUE TITLE
Terraform Provider Does Not Support Hyphen in Custom Properties Configuration

### ISSUE THREAD

**Issue by leij-splunk** [splunk/terraform-provider-synthetics#40]
**Description**:
The current version of the Terraform provider exhibits a limitation by not supporting hyphens in Custom Properties configuration. This deviation poses an inconsistency with the expected behavior and functionality.

**Additional Information:**
- Terraform Provider Version: v2.0.3
- Relevant Code Snippet:
   https://github.com/splunk/terraform-provider-synthetics/blob/cd6630800b5836a83367eabe3af6b45de3c7e64c/synthetics/resource_api_check_v2.go#L205
   https://github.com/splunk/terraform-provider-synthetics/blob/cd6630800b5836a83367eabe3af6b45de3c7e64c/synthetics/resource_api_check_v2.go#L210
- [Custom properties Document](https://docs.splunk.com/observability/en/synthetics/browser-test/set-up-browser-test.html#custom-properties): 
   - Key Requirements:
      - Must start with a letter.
      - **Allowed characters include letters, numbers, underscores, and hyphens.**
      - Naming restrictions: Can't be named test_id or test.
      - Character limit: Key size cannot exceed 128 characters.
   - Value Requirements:
      - **Allowed characters include letters, numbers, underscores, and hyphens.**

**Comment by greatestusername-splunk** [comment]
Thanks for adding this issue! Will double check the regex with the backend and if other chars are allowed update the validate function!

**Comment by bambro** [comment]
@greatestusername-splunk can you confirm the requirements of the property values? Hyphens and other special characters are allowed in the UI however are excluded by terraform

**Comment by greatestusername-splunk** [comment]
@bambro 
These should work in terraform now. Latest version included an updated regex for allowing hyphens and underscores.

**Comment by greatestusername-splunk** [comment]
Closing as https://github.com/splunk/terraform-provider-synthetics/pull/44 should address this issue in full. If it does not please re-open another issue.

Thanks!
