### ISSUE TITLE
Custom property values do not support hyphens

### ISSUE THREAD

**Issue by bambro** [splunk/terraform-provider-synthetics#48]
**Description:**
This issue extends from [issue #40](https://github.com/splunk/terraform-provider-synthetics/issues/40) to support hyphens in the custom property value, similar to the support that was added in for the key.

Currently the regex only supports alphanumeric characters and underscores with the following regex `/^[a-zA-Z0-9](\w|_){1,128}$` and should be extended to `/^[a-zA-Z0-9](\w|-|_){1,128}$`.

**Additional Information:**
- Terraform Provider Version: **v2.0.5**
- Relevant Snippet:
https://github.com/splunk/terraform-provider-synthetics/blob/3d51d056b69a01daa3713eb166fdfe2223cf3846/synthetics/resource_api_check_v2.go#L211

**Comment by greatestusername** [comment]
Good catch! Thought the hyphen had gotten into all of them in 40!
Are you at all interested in contributing a quick PR?
